# 日志配置
#logging:
#  config: classpath:log4j2-dev.xml

# 数据源配置
spring:
  datasource:
    url: jdbc:mysql://192.168.142.208:3306/b2b?useAffectedRows=true&userUnicode=true&characterEncoding=utf8&pinGlobalTxToPhysicalConnection=true&serverTimezone=GMT%2b8
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

env:
  dev

# sql日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl