# 日志配置
#logging:
#  config: classpath:log4j2-dev.xml

#spring:
#  shardingsphere:
#    datasource:
#      b2b1:
#        type: com.alibaba.druid.pool.DruidDataSource
#        driver-class-name: com.mysql.cj.jdbc.Driver
#        url: jdbc:mysql://192.168.142.208:3306/b2b_1?useAffectedRows=true&userUnicode=true&characterEncoding=utf8&pinGlobalTxToPhysicalConnection=true&serverTimezone=GMT%2b8
#        username: root
#        password: root
#      b2b2:
#        type: com.alibaba.druid.pool.DruidDataSource
#        driver-class-name: com.mysql.cj.jdbc.Driver
#        url: jdbc:mysql://192.168.142.208:3306/b2b_2?useAffectedRows=true&userUnicode=true&characterEncoding=utf8&pinGlobalTxToPhysicalConnection=true&serverTimezone=GMT%2b8
#        username: root
#        password: root

#spring:
#  datasource:
#    url: jdbc:mysql://192.168.142.208:3306/b2b_1?useAffectedRows=true&userUnicode=true&characterEncoding=utf8&pinGlobalTxToPhysicalConnection=true&serverTimezone=GMT%2b8
#    username: root
#    password: root
#    driverClassName: com.mysql.cj.jdbc.Driver
#    type: com.alibaba.druid.pool.DruidDataSource

env:
  dev

# sql日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


