# 默认使用配置环境
spring:
  application:
    name: sharding
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  main:
    banner-mode: console

  #数据源需要自己配置
  shardingsphere:
    datasource:
      b2b0:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://192.168.142.208:3306/b2b_0?useAffectedRows=true&userUnicode=true&characterEncoding=utf8&pinGlobalTxToPhysicalConnection=true&serverTimezone=GMT%2b8
        username: root
        password: root
      b2b1:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://192.168.142.208:3306/b2b_1?useAffectedRows=true&userUnicode=true&characterEncoding=utf8&pinGlobalTxToPhysicalConnection=true&serverTimezone=GMT%2b8
        username: root
        password: root

#端口号
server:
  port: 8678


# Mybatis配置地址
#mybatis:
#  mapper-locations: classpath:/mapper/**/*.xml
#  config-location: classpath:mybatis-config.xml
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  type-aliases-package: com.nala.sharding.domain
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

#日期格式统一
spring.jackson.date-format: yyyy-MM-dd HH:mm:ss
spring.jackson.time-zone: GMT+8
